---
metadata:
  name: Namaz radost oka moga
  short_name: BooGi
  description: BooGi - awesome GitBook-like documentation generator using Gatsby
  language: en
  pathPrefix: '/'
  siteImage: '/assets/slika.png'
  favicon: '/assets/favicon.png'
  themeColor: '#ff0000'
header:
  enabled: true
  logo: '/assets/code.svg'
  logoLink: '/'
  helpUrl: ''
  links:
    - text: BooGi
      link: https://github.com/filipowm/boogi
      external: true
    - text: Gatsby
      link: https://www.gatsbyjs.org
      external: true
    - text: Docs
      link: '/'
      external: false
sidebar:
  enabled: true
  # forcedNavOrder:
  #   - "/introduction"
  #   - "/configuration/basic"
  #   - "/configuration/advanced"
  # expanded:
  groups:
    - order: 1
      path: '/vrijednostnamaza'
      title: ':rocket: Vrijednost namaza'
    - order: 2
      path: '/greskeunamazu'
      title: ':wrench: Greške u namazu'
    - order: 3
      path: '/skrusenostunamazu'
      title: ':wrench: Skrušenost u namazu'

  links:
    # - text: BooGi
    #   link: https://github.com/filipowm/boogi
    # - text: React
    #   link: https://reactjs.org
  ignoreIndex: false
  poweredBy:
    # trademark: '/assets/gatsby.png'
    # name: GatsbyJS
    # link: https://www.gatsbyjs.org
pwa:
  enabled: true
  manifest:
    display: standalone
    crossOrigin: anonymous
    icon: '/assets/favicon.png'

social:
  github: https://github.com/filipowm/boogi
  linkedin: https://www.linkedin.com/in/mateusz-filipowicz-437b4768/
  twitter: twitter url

features:
  darkMode:
    enabled: true
    default: false
  editOnRepo:
    location: https://github.com/filipowm/boogi
    type: github
    editable: false
  mermaid:
    language: 'mermaid'
    theme: 'dark'
    options:
    width: 400
    height: 300
  pageProgress:
    enabled: true
    includePaths:
      - '/configuration/settingup/features'
    excludePaths:
      - '/'
    height: 3
    prependToBody: false
    color: '#A05EB5'
  previousNext:
    enabled: true
    arrowKeyNavigation: true
  propagateNetlifyEnv: true
  rss:
    enabled: true
    title: BooGi Docs
    showIcon: false
    copyright: 'Elvedin Pezić'
    webMaster: 'Elvedin Pezić'
    managingEditor: 'Elvedin Pezić'
    categories:
      - Docs as Code
      - GatsbyJS
    ttl: 60
    matchRegex: '^/'
    outputPath: '/rss.xml'
    generator: 'boogi'
  scrollTop: true
  search:
    enabled: true
    engine: 'localsearch'
    placeholder: 'Search'
    startComponent: 'input' # icon
    excerptSize: 20000
    debounceTime: 380
    snippetLength: 23
    hitsPerPage: 10
    showStats: true
    pagination:
      enabled: true
      totalPages: 10
      showPrevious: true
      showNext: true
  showMetadata: true
  toc:
    show: true
    depth: 4
  fullScreenMode:
    enabled: true
    hideHeader: true
    hideToc: true
    hideSidebar: true
